# Remove this step completely
- name: Download minimal AOSP base
  run: |
    mkdir aosp-minimal
    cd aosp-minimal
    git init
    git remote add origin https://android.googlesource.com/platform/manifest
    git fetch --depth 1 android-12.0.0_r1
    git checkout FETCH_HEAD
    echo "Downloaded minimal AOSP manifest"

