name: AOSP Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build AOSP Kiosk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install AOSP dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev \
            gcc-multilib g++-multilib libc6-dev-i386 libncurses5-dev \
            x11proto-core-dev libx11-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig

      - name: Cache build output
        uses: actions/cache@v4
        with:
          path: |
            ~/.ccache
            out
          key: ${{ runner.os }}-aosp-${{ hashFiles('**/Android.mk', '**/Android.bp') }}
          restore-keys: |
            ${{ runner.os }}-aosp-

      - name: Build AOSP kiosk image
        run: |
          source build/envsetup.sh
          lunch aosp_arm-eng
          make -j$(nproc) kiosk

      - name: Upload AOSP output
        uses: actions/upload-artifact@v4
        with:
          name: aosp-build-output
          path: out/target/product/

